
/**************************************************************
 *	
 *	biteSoundFX, 8 bit, 44100Hz,
 *	1 channel, 27608 bytes/channel
 *	Total Size: 1 * 27608 + 4 (header) = 27652 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	\\prism.nas.gatech.edu\esapp3\vlab\downloads\wav2c\wav2c\biteSoundFX.wav
 *	Time-stamp: Tue Apr 22 22:26:03 2014
 *	
 **************************************************************/

#ifndef __BITESOUNDFXH__
#define __BITESOUNDFXH__

#define BITESOUNDFXFREQ 44100
#define BITESOUNDFXLEN 27608

extern const unsigned char biteSoundFX[27608];

#endif /* __BITESOUNDFXH__ */
