
/**************************************************************
 *	
 *	duckieSong, 8 bit, 22050Hz,
 *	1 channel, 382277 bytes/channel
 *	Total Size: 1 * 382277 + 4 (header) = 382321 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	\\prism.nas.gatech.edu\esapp3\vlab\downloads\wav2c\wav2c\duckieSong.wav
 *	Time-stamp: Tue Apr 22 21:30:55 2014
 *	
 **************************************************************/

#ifndef __DUCKIESONGH__
#define __DUCKIESONGH__

#define DUCKIESONGFREQ 22050
#define DUCKIESONGLEN 382277

extern const unsigned char duckieSong[382277];

#endif /* __DUCKIESONGH__ */
