
/**************************************************************
 *	
 *	sound4, 8 bit, 44100Hz,
 *	1 channel, 304290 bytes/channel
 *	Total Size: 1 * 304290 + 4 (header) = 304334 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	\\prism.nas.gatech.edu\esapp3\vlab\desktop\sound4.wav
 *	Time-stamp: Fri Apr 25 03:39:30 2014
 *	
 **************************************************************/

#ifndef __SOUND4H__
#define __SOUND4H__

#define SOUND4FREQ 44100
#define SOUND4LEN 304290

extern const unsigned char sound4[304290];

#endif /* __SOUND4H__ */
